modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/OnyxStudios/Project-I/issues/"

[[mods]]
modId="projecti"
version="${file.jarVersion}"
displayName="Project I"
displayURL="https://github.com/OnyxStudios/Project-I/"
logoFile="logo.png"
credits="Intangible for being the inspiration for this mod"
authors="abused_master"
description='''
A mod that allows players to explore the intangible energies that make up creatures and deities, and by learning to use these forces they are able to create the appearence of magical powers!
'''